spring:
  application:
    name: cloudbalance

  datasource:
    url: jdbc:mysql://localhost:3306/CloudBalance
    username: root
    password: mohit@123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update

logging:
  level:
    org.springframework.security: DEBUG

server:
  port: 5555
